DROP POLICY IF EXISTS player_resources_select_all ON player_resources;
CREATE POLICY player_resources_select_all ON player_resources FOR SELECT USING (true);
DROP POLICY IF EXISTS player_buildings_select_all ON player_buildings;
CREATE POLICY player_buildings_select_all ON player_buildings FOR SELECT USING (true);
DROP POLICY IF EXISTS player_research_select_all ON player_research;
CREATE POLICY player_research_select_all ON player_research FOR SELECT USING (true);
DROP POLICY IF EXISTS player_commander_select_all ON player_commander;
CREATE POLICY player_commander_select_all ON player_commander FOR SELECT USING (true);
DROP POLICY IF EXISTS player_fleet_select_all ON player_fleet;
CREATE POLICY player_fleet_select_all ON player_fleet FOR SELECT USING (true);
DROP POLICY IF EXISTS player_hangar_select_all ON player_hangar;
CREATE POLICY player_hangar_select_all ON player_hangar FOR SELECT USING (true);
DROP POLICY IF EXISTS player_ship_designs_select_all ON player_ship_designs;
CREATE POLICY player_ship_designs_select_all ON player_ship_designs FOR SELECT USING (true);
DROP POLICY IF EXISTS player_blueprints_select_all ON player_blueprints;
CREATE POLICY player_blueprints_select_all ON player_blueprints FOR SELECT USING (true);
DROP POLICY IF EXISTS player_blueprint_fragments_select_all ON player_blueprint_fragments;
CREATE POLICY player_blueprint_fragments_select_all ON player_blueprint_fragments FOR SELECT USING (true);
DROP POLICY IF EXISTS player_commanders_select_all ON player_commanders;
CREATE POLICY player_commanders_select_all ON player_commanders FOR SELECT USING (true);
DROP POLICY IF EXISTS player_deployed_commanders_select_all ON player_deployed_commanders;
CREATE POLICY player_deployed_commanders_select_all ON player_deployed_commanders FOR SELECT USING (true);
DROP POLICY IF EXISTS player_colonies_select_all ON player_colonies;
CREATE POLICY player_colonies_select_all ON player_colonies FOR SELECT USING (true);
DROP POLICY IF EXISTS player_instance_progress_select_all ON player_instance_progress;
CREATE POLICY player_instance_progress_select_all ON player_instance_progress FOR SELECT USING (true);
DROP POLICY IF EXISTS player_missions_select_all ON player_missions;
CREATE POLICY player_missions_select_all ON player_missions FOR SELECT USING (true);
DROP POLICY IF EXISTS player_achievements_select_all ON player_achievements;
CREATE POLICY player_achievements_select_all ON player_achievements FOR SELECT USING (true);
DROP POLICY IF EXISTS player_artifacts_select_all ON player_artifacts;
CREATE POLICY player_artifacts_select_all ON player_artifacts FOR SELECT USING (true);
DROP POLICY IF EXISTS player_pvp_select_all ON player_pvp;
CREATE POLICY player_pvp_select_all ON player_pvp FOR SELECT USING (true);
DROP POLICY IF EXISTS player_espionage_select_all ON player_espionage;
CREATE POLICY player_espionage_select_all ON player_espionage FOR SELECT USING (true);
DROP POLICY IF EXISTS player_formations_select_all ON player_formations;
CREATE POLICY player_formations_select_all ON player_formations FOR SELECT USING (true);
DROP POLICY IF EXISTS player_recycle_queue_select_all ON player_recycle_queue;
CREATE POLICY player_recycle_queue_select_all ON player_recycle_queue FOR SELECT USING (true);
DROP POLICY IF EXISTS player_build_queue_select_all ON player_build_queue;
CREATE POLICY player_build_queue_select_all ON player_build_queue FOR SELECT USING (true);
DROP POLICY IF EXISTS player_pack_pity_select_all ON player_pack_pity;
CREATE POLICY player_pack_pity_select_all ON player_pack_pity FOR SELECT USING (true);
DROP POLICY IF EXISTS player_conquered_planets_select_all ON player_conquered_planets;
CREATE POLICY player_conquered_planets_select_all ON player_conquered_planets FOR SELECT USING (true);
DROP POLICY IF EXISTS player_jump_gate_cooldowns_select_all ON player_jump_gate_cooldowns;
CREATE POLICY player_jump_gate_cooldowns_select_all ON player_jump_gate_cooldowns FOR SELECT USING (true);
DROP POLICY IF EXISTS player_boss_cooldowns_select_all ON player_boss_cooldowns;
CREATE POLICY player_boss_cooldowns_select_all ON player_boss_cooldowns FOR SELECT USING (true);
DROP POLICY IF EXISTS player_drop_pity_select_all ON player_drop_pity;
CREATE POLICY player_drop_pity_select_all ON player_drop_pity FOR SELECT USING (true);
DROP POLICY IF EXISTS player_misc_state_select_all ON player_misc_state;
CREATE POLICY player_misc_state_select_all ON player_misc_state FOR SELECT USING (true);
